version: '3.7'

services:

  client:
    container_name: chat_app_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=development

  server:
    container_name: chat_app_server
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - '8000'
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development