version: '3.7'

services:

  client:
    container_name: client_production
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=development

  server:
    container_name: server_production
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development