export const SOCKET_CONNECT = 'SOCKET_CONNECT'
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT'

export const SET_NAME = 'SET_NAME'

export const SET_TOAST = 'SET_TOAST'
export const REMOVE_TOAST = 'REMOVE_TOAST'
